### PR TITLE
Add command to rename items with color codes

### PR DESCRIPTION
**Pull request by phase**
`/rename &cblah` will rename the item in your main hand to `blah` with the color of light red.

### CODE REVIEW

**Comment by wgaylord** [comment]
OKAY! Also about the horrible tabs vs spaces blame having to fix permissions from an ipad while on the road to St Louis.

**Comment by phase** [comment]
sounds horrible but ok

**Comment by wgaylord** [comment]
I have not had to open it in eclipse again yet.... :(

**Comment by phase** [comment]
IntelliJ is so much better ;)

**Comment by wgaylord** [comment]
so is nano. :P also lets not have a argument here considering this posts into an ORE slack channel.

**Pull request merged**
